apiVersion: v1
kind: Pod
metadata:
  labels:
    rabbitnode: rabbitmq1
    component: rabbitmq
  name: rabbitmq1
spec:
  volumes:
  - name: storage
    emptyDir: {}
  containers:
  - name: rabbitmq1
    imagePullPolicy: Always
    image: andrewwebber/k8-rabbitmq
    volumeMounts:
      - name: storage
        mountPath: /var/lib/rabbitmq
    env:
      - name: RABBITMQ_NODENAME
        value: "rabbit"
      - name: RABBITMQ_ERLANG_COOKIE
        value: "rabbit"
    ports:
    - name: rabbitmq
      containerPort: 5672
    - name: management
      containerPort: 15672
    - name: epmd
      containerPort: 4369
    - name: erlang
      containerPort: 25672
    resources:
      limits:
        cpu: 100m
---
apiVersion: v1
kind: Service
metadata:
  labels:
    rabbitnode: rabbitmq1
  name: rabbitmq1
spec:
  ports:
  - port: 5672
    name: rabbitmq
  - port: 15672
    name: management
  - name: epmd
    port: 4369
  - name: erlang
    port: 25672
  clusterIP: None
  selector:
    rabbitnode: rabbitmq1
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    rabbitnode: rabbitmq2
    component: rabbitmq
  name: rabbitmq2
spec:
  volumes:
  - name: storage
    emptyDir: {}
  containers:
  - name: rabbitmq2
    imagePullPolicy: Always
    image: andrewwebber/k8-rabbitmq
    volumeMounts:
      - name: storage
        mountPath: /var/lib/rabbitmq
    env:
      - name: RABBITMQ_NODENAME
        value: "rabbit"
      - name: RABBITMQ_ERLANG_COOKIE
        value: "rabbit"
    ports:
    - name: rabbitmq
      containerPort: 5672
    - name: management
      containerPort: 15672
    - name: epmd
      containerPort: 4369
    - name: erlang
      containerPort: 25672
    resources:
      limits:
        cpu: 100m
---
apiVersion: v1
kind: Service
metadata:
  labels:
    rabbitnode: rabbitmq2
  name: rabbitmq2
spec:
  ports:
  - port: 5672
    name: rabbitmq
  - port: 15672
    name: management
  - name: epmd
    port: 4369
  - name: erlang
    port: 25672
  clusterIP: None
  selector:
    rabbitnode: rabbitmq2
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    rabbitnode: rabbitmq3
    component: rabbitmq
  name: rabbitmq3
spec:
  volumes:
  - name: storage
    emptyDir: {}
  containers:
  - name: rabbitmq3
    imagePullPolicy: Always
    image: andrewwebber/k8-rabbitmq
    volumeMounts:
      - name: storage
        mountPath: /var/lib/rabbitmq
    env:
      - name: RABBITMQ_NODENAME
        value: "rabbit"
      - name: RABBITMQ_ERLANG_COOKIE
        value: "rabbit"
    ports:
    - name: rabbitmq
      containerPort: 5672
    - name: management
      containerPort: 15672
    - name: epmd
      containerPort: 4369
    - name: erlang
      containerPort: 25672
    resources:
      limits:
        cpu: 100m
---
apiVersion: v1
kind: Service
metadata:
  labels:
    rabbitnode: rabbitmq3
  name: rabbitmq3
spec:
  ports:
  - port: 5672
    name: rabbitmq
  - port: 15672
    name: management
  - name: epmd
    port: 4369
  - name: erlang
    port: 25672
  clusterIP: None
  selector:
    rabbitnode: rabbitmq3
---
apiVersion: v1
kind: Service
metadata:
  labels:
    component: rabbitmq
  name: rabbitmq-service
spec:
  ports:
  - port: 5672
    name: rabbitmq
  - port: 15672
    name: management
  - name: epmd
    port: 4369
  - name: erlang
    port: 25672
  clusterIP: None
  selector:
    component: rabbitmq
